### ISSUE TITLE
[Bug] One to many relations

### ISSUE THREAD

**Issue by SebastianM** [glerchundi/sqlboiler-crdb#16]
Hey,

thanks for developing this driver. It worked pretty good so far but I think I discovered a bug in one to many relations. Here's my schema:
```sql

CREATE TABLE pilots (
  id integer NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (id ASC),
  name text NOT NULL
);


CREATE TABLE jets (
  id integer NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (id ASC),
  pilot_id integer NOT NULL,
  age integer NOT NULL,
  name text NOT NULL,
  color text NOT NULL,
  INDEX idx_device_id (pilot_id ASC)
);
```

It generated the following relation:

```go
// pilotR is where relationships are stored.
type pilotR struct {
	Jet *Jet
}
```

But I would expect the following struct:
```go
type pilotR struct {
  Jets      JetSlice
}
```

Am I missing something to create a one to many relation? Thanks in advance!

**Comment by SebastianM** [comment]
After updating to the newest version, it worked. I think it was this bugfix: https://github.com/glerchundi/sqlboiler-crdb/commit/8165fe292c2c4afb97502ec5c899cb74245b3bbc

**Comment by glerchundi** [comment]
Great, glad to see issues closed without touching the code!
